version: "3.8"
services:
  app:
    env_file:
      - .env
    image: care-bridge  # Docker Hub에서 herokim97/codesix 이미지를 사용
    ports:
      - "8080:8080"

    depends_on:
      - mysql
      - redis
  #    restart: always
  redis:
    image: redis:latest   # Redis 공식 이미지
    container_name: redis_container  # 컨테이너 이름
    ports:
      - "6379:6379"       # Redis 기본 포트
    restart: always

  mysql:
    image: mysql:8.0  # 공식 MySQL 이미지 사용
    environment:
      MYSQL_DATABASE: care_bridge
      MYSQL_ROOT_PASSWORD: gksl671456!
      DATABASE_USERNAME: root
      DATABASE_PASSWORD: gksl671456!
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
    driver: local