version: "3.8"
services:
  app:
    image: herokim97/carebridge:latest  # Docker Hub에서 herokim97/codesix 이미지를 사용
    ports:
      - "8080:8080"
    environment:
      - URL=jdbc:mysql://mysql:3306/care_bridge
      - DATABASE_USERNAME=${DB_USERNAME}
      - DATABASE_PASSWORD=${DB_PASSWORD}
      # 버킷 설정
      - ACCESS_KEY=${ACCESS_KEY}
      - SECRET_KEY=${SECRET_KEY}
      - BUCKET_NAME=${BUCKET_NAME}
      # Google Social Login 설정
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - REDIRECT_URI=${REDIRECT_URI}
      # AI Chat 설정
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - KAKAO_PAY_SECRET_KEY=${KAKAO_PAY_SECRET_KEY}
    depends_on:
      - mysql  # mysql 서비스에 의존
  #    restart: always

  mysql:
    image: mysql:8.0  # 공식 MySQL 이미지 사용
    environment:
      MYSQL_DATABASE: care_bridge
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      DATABASE_USERNAME: ${DB_USERNAME}
      DATABASE_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
#    volumes:
#      - mysql-data:/var/lib/mysql

#volumes:
#  mysql-data:
#    driver: local